### ISSUE TITLE
CI workflows break because of missing ilcsoft setup

### ISSUE THREAD

**Issue by tmadlener** [iLCSoft/MarlinUtil#19]
The nightly build of clicdp that we used up until now, based on LCG_97, has been replaced by one based on LCG_100. This will probably affect all the CI workflows of iLCSoft. Opening this issue here to keep track of it.

See here for the current error:
https://github.com/iLCSoft/MarlinUtil/runs/3377587077?check_suite_focus=true#step:4:14

Currently affected packages (i.e. packages where a workflow has failed up until now):
- [ ] MarlinUtil (coverity)
- [ ] LCTuple (coverity)
- [ ] Overlay (coverity)

**Comment by andresailer** [comment]
Mea Culpa, but also that installation hasn't been updated in some time and probably wouldn't have worked because of
I'm trying to create builds with gcc10 opt and dbg, and with clang11 based on LCG_100

**Comment by tmadlener** [comment]
Would it be easily possible to still have an environment with python2 and gcc8, since the latest release we have is still based on that?

**Comment by andresailer** [comment]
I can try using LCG_99python2 for that

**Comment by tmadlener** [comment]
That would be awesome, thanks.

**Comment by andresailer** [comment]
The three packages mentioned above, and some more, have been modified for the new builds.
