### ISSUE TITLE
Suggestion for a method to return TPC radii

### ISSUE THREAD

**Issue by dudarboh** [iLCSoft/MarlinUtil#22]
### Feature suggestion

Wouldn't it be nice to have an easy way to get tpc outer and inner radii?

### Current approach

requires 5 lines which could be hidden under one marlinUtil method:

```
dd4hep::Detector& det = dd4hep::Detector::getInstance();
dd4hep::DetElement tpcDet = det.detector("TPC") ;
const dd4hep::rec::FixedPadSizeTPCData* tpc = tpcDet.extension<dd4hep::rec::FixedPadSizeTPCData>() ;
double tpcInnerR = tpc->rMinReadout/dd4hep::mm;
double tpcOuterR = tpc->rMaxReadout/dd4hep::mm;
```

### It is extensively used in many Marlin processors:

1. [Clupatra/src/ClupatraProcessor.cc](https://github.com/iLCSoft/Clupatra/blob/f43b86e590872d82fba9e79f51c728283804dc3a/src/ClupatraProcessor.cc)
2. [MarlinTrkProcessors/source/Digitisers/src/TPCModularEndplate.cc](https://github.com/iLCSoft/MarlinTrkProcessors/blob/363e01c9c1f4f98fd62d3c81f648abe72c00756a/source/Digitisers/src/TPCModularEndplate.cc)
2. [MarlinTrkProcessors/source/Digitisers/src/DDTPCDigiProcessor.cc](https://github.com/iLCSoft/MarlinTrkProcessors/blob/363e01c9c1f4f98fd62d3c81f648abe72c00756a/source/Digitisers/src/DDTPCDigiProcessor.cc)
3.  [MarlinTrkProcessors/source/Digitisers/src/FixedPadSizeDiskLayout.cc](https://github.com/iLCSoft/MarlinTrkProcessors/blob/363e01c9c1f4f98fd62d3c81f648abe72c00756a/source/Digitisers/src/FixedPadSizeDiskLayout.cc)
4.  [MarlinReco/Analysis/PIDTools/src/Compute_dEdxProcessor2021.cc](https://github.com/iLCSoft/MarlinReco/blob/dc19a41b2255666eeac8f90c7cf7f8633e1dd2c6/Analysis/PIDTools/src/Compute_dEdxProcessor2021.cc)
5. [MarlinReco/Analysis/PIDTools/src/Compute_dEdxProcessor.cc](https://github.com/iLCSoft/MarlinReco/blob/39201c6fbfc257a30e4bb86c7e2eacca908a6729/Analysis/PIDTools/src/Compute_dEdxProcessor.cc)
7. [MarlinReco/Tracking/KinkFinder/src/KinkFinder.cc](https://github.com/iLCSoft/MarlinReco/blob/39201c6fbfc257a30e4bb86c7e2eacca908a6729/Tracking/KinkFinder/src/KinkFinder.cc) 
8. [MarlinReco/TimeOfFlight/src/TOFEstimators.cc](https://github.com/iLCSoft/MarlinReco/blob/master/TimeOfFlight/src/TOFUtils.cc) (soon)
9. [ILDPerformance/dEdX/src/dEdxAnalyser.cc](https://github.com/iLCSoft/ILDPerformance/blob/c313f0515698fd68a72f324706ae3589a2fe26d9/dEdX/src/dEdxAnalyser.cc)

**Comment by dudarboh** [comment]
Hi @tmadlener,

Thanks again for the very detailed feedback.

After giving it a little thought, I think creating another wrapping struct is a little bit overkill.
As what are the "most commonly used parameters" is somewhat depends on the perspective.
And it has a little sense to create a new struct copying all the fields and just ensuring that they are in mm by default, rather than in cm.

Also renaming `tpcData->rMaxReadout` as e.g. `outerRadius` can be misleading in a very subtle cases, where one might want `tpcData->rMax` which is not the same. So creating "more convenient" naming is also dangerous.

So, I would just go with creating a helper function that returns a pointer to the e.g. `FixedPadSizeTPCData*`

But, maybe then it would make sense to create something like this for all tracker detectors?
As the most confusing part for me as a user is to guess all the time which extension type corresponds to which detector.

Taking as an example code from `KinkFinder.cc`:
```
dd4hep::DetElement tpcDE = theDet.detector("TPC") ;
const dd4hep::rec::FixedPadSizeTPCData* tpc = tpcDE.extension<dd4hep::rec::FixedPadSizeTPCData>() ;

dd4hep::DetElement vtxDE = theDet.detector("VXD");
dd4hep::rec::ZPlanarData* vtx = vtxDE.extension<dd4hep::rec::ZPlanarData>();

dd4hep::DetElement sitDE = theDet.detector("SIT");
dd4hep::rec::ZPlanarData* sit = sitDE.extension<dd4hep::rec::ZPlanarData>();
```

Why `VXD` and `SIT` detectors have the same extension type `ZPlanarData`, as `VXD` supposed to be pixel detector, but not strip (it has nothing "planar")?
What extensions shall I use if I want to access `FTD`? Is it also `ZPlanarData`? Or `ZDiskPetalsData`? Or `ConicalSupportData`?  
What extensions shall I use if I want to access `SET` data? Is SET accessible at all through the extensions?

These are most confusing points... And it would be helpful to have something like: 
```
//return type varies based on input...
auto* theDet.getDetectorData("SIT")
```
It would require user to know only the name of the detector. If it doesn't exist, one can print available detectors.. And no need to guess the type of the extension..

But, this is probably not doable in one method, as compiler needs to know return type..
So one could probably create one method per each detector as we discussed above starting with the tpc..

any thoughts?

**Comment by tmadlener** [comment]
I agree, I think just having a function that gives you the appropriate extension pointer is something that would indeed be very useful.

> But, this is probably not doable in one method, as compiler needs to know return type..
So one could probably create one method per each detector as we discussed above starting with the tpc..

The easiest solution is probably to create one method per detector, not only from an implementation point of view but also from a user point of view. Since in that case the name of the detector is already in the function name, you could also make the name parameter optional (or remove it completely).


> Why VXD and SIT detectors have the same extension type `ZPlanarData`, as VXD supposed to be pixel detector, but not strip (it has nothing "planar")?
What extensions shall I use if I want to access FTD? Is it also `ZPlanarData`? Or `ZDiskPetalsData`? Or `ConicalSupportData`?
What extensions shall I use if I want to access SET data? Is SET accessible at all through the extensions?

I can't really answer that, but @gaede might be able to give some more insights here.

**Comment by dudarboh** [comment]
Hi @tmadlener,
I created a pull request which would return extensions for every detector element as we discussed, please have a look, when you have time.

Maybe few items for follow up discussion:
 - Do these extensions still valid for SiW detector? Is it better to specify that this is ILD specific?
 - I thought to add documentation  explaining parameters you can extract and their default units.
 But then it is a lot to copy from dd4hep if we include as well struct helpers for each layer e.g. [here](https://github.com/AIDASoft/DD4hep/blob/b95823997380f0d6f023e05e5705acd27993e945/DDRec/include/DDRec/DetectorData.h#L219-L241)..
 Copying dd4hep looks not nice, as within any changes, our documentation gets outdated..
 Maybe we can refer simply to the dd4hep class? Explanations there are not extensive, but sufficient
 
 Any thoughts?
